### ISSUE TITLE
You do not have permission to view this resource.

### ISSUE THREAD

**Issue by Techno-Fox** [fkie-cad/LuckyCAT#2]
I'm getting this error when trying to create a new user. 

You do not have permission to view this resource.

P.S. Thanks for working on this project.

**Comment by caioluders** [comment]
Default user:password in on https://github.com/fkie-cad/LuckyCAT/blob/3d106ad5f71db9575148292daa0780c0b65572a5/luckycat/f3c_global_config.py 

Btw, this is a bad security practice guys, you know that

**Comment by 0xricksanchez** [comment]
As this was never meant to be a hardened web application that is connected to the internet we never much prioritized adding a hardened authentication mechanism. As @caioluders already said there is a default admin user with hard-coded credentials.
