### ISSUE TITLE
How to set up job consumers?

### ISSUE THREAD

**Issue by qlyoung** [fkie-cad/LuckyCAT#3]
I've successfully deployed the project, created a job, and spent a while poking around, but it's not clear to me how to actually get a fuzzer to run the job. As I understand it, the builtin fuzzers are in the `fuzzers` directory in the project root, and they're supposed to get jobs from RabbitMQ running in the `queue` container, which handles various queues shared among the rest of the containers, to run. But are there any actually ready-to-go fuzzers implemented in this project, or are you supposed to just write your own? Seems like a really cool project and I'd like to use it.

**Comment by Kankarollo** [comment]
Same thing. I've created new job to test AFL fuzzing but what's next? How to actually start it.

**Comment by qlyoung** [comment]
@Kankarollo shameless plug - I ended up writing my own distributed fuzzing platform, may be of interest to you
https://github.com/qlyoung/lagopus

**Comment by 0xricksanchez** [comment]
Sorry for the delay @qlyoung @Kankarollo . We're aware that LuckyCat has problems on many fronts. As all original maintainers are no longer working with us there is no guaranteed update/support for this framework in the foreseeable future.

Regarding starting jobs: It's not done automatically. You still have to invoke the `afl-luckycat.py` as shown in here: https://github.com/fkie-cad/LuckyCAT/tree/master/luckycat/fuzzers/aflfuzz

We still believe that a local fuzzing cluster framework like LuckyCat (with some new major tweaks :)) has large potential. Eventually, we'd like to support and re-write large portions to make it more intuitive. Feel free to fork/PR! In the latter case I'll timely review the PR and merge it into master

Cheers
